package:
  name: trefide
  version: "2.0"

source:
  path: ../

build:
  number: 0
  
requirements:
  build:
    - intel::python>=3.6
    - intel::numpy
    - intel::scipy
    - intel::matplotlib
    - intel::mkl-devel {{ mkl }}
    - intel::cython=0.27.3

  run:
    - intel::python>=3.6
    - intel::numpy
    - intel::scipy
    - intel::matplotlib
    - intel::mkl {{ mkl }}
    - intel::jupyter
    - intel::scikit-learn
    - menpo::opencv3

test:
    #  imports:
    #- trefide.pmd

about:
  home: https://github.com/ikinsella/trefide
  license: GPL
  license_family: GPL3
  license_file: LICENSE
